/*

export const DELETE_POST = "DELETE_POST";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const GET_POSTS = "GET_POSTS";

export const UPDATE_POST = "UPDATE_POST";
export const DELETE_COMMENT = "DELETE_COMMENT"; 


export const POSTS_LIST_FAIL = "POSTS_LIST_FAIL";
export const POSTS_LIST_REQUEST = "POSTS_LIST_REQUEST";
export const POSTS_LIST_SUCCESS = "POSTS_LIST_SUCCESS";

*/

export const COMMENTS_LIST_REQUEST = "NOTES_LIST_REQUEST";
export const COMMENTS_LIST_SUCCESS = "NOTES_LIST_SUCCESS";
export const COMMENTS_LIST_FAIL = "NOTES_LIST_FAIL";

export const COMMENTS_DELETE_REQUEST = "COMMENTS_DELETE_REQUEST";
export const COMMENTS_DELETE_SUCCESS = "COMMENTS_DELETE_SUCCESS";
export const COMMENTS_DELETE_FAIL = "COMMENTS_DELETE_FAIL";

export const POSTS_UPDATE_REQUEST = "NOTES_UPDATE_REQUEST";
export const POSTS_UPDATE_SUCCESS = "NOTES_UPDATE_SUCCESS";
export const POSTS_UPDATE_FAIL = "NOTES_UPDATE_FAIL";

export const POSTS_DELETE_REQUEST = "NOTES_DELETE_REQUEST";
export const POSTS_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS";
export const POSTS_DELETE_FAIL = "NOTES_DELETE_FAIL";

export const GET_POSTS = "GET_POSTS";
export const GET_COMMENTS = "GET_COMMENTS";

export const COMMENTS_UPDATE_REQUEST = "COMMENTS_UPDATE_REQUEST";
export const COMMENTS_UPDATE_SUCCESS = "COMMENTS_UPDATE_SUCCESS";
export const COMMENTS_UPDATE_FAIL = "COMMENTS_UPDATE_FAIL";

