export const COMMENTS_DELETE_REQUEST = "COMMENTS_DELETE_REQUEST";
export const COMMENTS_DELETE_SUCCESS = "COMMENTS_DELETE_SUCCESS";
export const COMMENTS_DELETE_FAIL = "COMMENTS_DELETE_FAIL";

export const POSTS_UPDATE_REQUEST = "NOTES_UPDATE_REQUEST";
export const POSTS_UPDATE_SUCCESS = "NOTES_UPDATE_SUCCESS";
export const POSTS_UPDATE_FAIL = "NOTES_UPDATE_FAIL";

export const POSTS_DELETE_REQUEST = "NOTES_DELETE_REQUEST";
export const POSTS_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS";
export const POSTS_DELETE_FAIL = "NOTES_DELETE_FAIL";



